version: "3"
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.15
      container_name: elastic_elk
      restart: always
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - elasticsearch-volume:/var/lib/elasticsearch
      environment:
        - node.name=elasticsearch
        - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
        - discovery.type=single-node
        - thread_pool.bulk.queue_size=100000

    telegraf:
      image: telegraf:1.13-alpine
      container_name: telegraf_elk
      restart: always
      ports:
        - 57555:57555
      volumes:
        - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      depends_on:
        - elasticsearch
    
    kibana:
      image: docker.elastic.co/kibana/kibana:5.6.15
      container_name: kibana_elk
      restart: always
      ports:
        - 5601:5601
      volumes:
        - kibana-volume:/var/lib/kibana
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      depends_on:
        - elasticsearch

volumes:
  elasticsearch-volume:
    external: true
  kibana-volume:
    external: true